kind: Pod
apiVersion: v1
metadata:
  generateName: mysql-65647c574b-
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.6.139/23"],"mac_address":"0a:58:0a:80:06:8b","gateway_ips":["10.128.6.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.6.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.6.1"},{"dest":"169.254.0.5/32","nextHop":"10.128.6.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.6.1"}],"ip_address":"10.128.6.139/23","gateway_ip":"10.128.6.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.6.139"
          ],
          "mac": "0a:58:0a:80:06:8b",
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container mysql; cpu, memory limit for container mysql'
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '4058178180'
  name: mysql-65647c574b-6qb95
  uid: ea4093f3-a91d-4abe-8c36-5fe80a8ab3fd
  creationTimestamp: '2025-08-14T12:27:28Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-08-14T12:27:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:deployment': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"5f70d28c-08f6-4b0c-8b03-861f2658824d"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"mysql"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/bitnami/mysql"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:env':
                .: {}
                'k:{"name":"MYSQL_DATABASE"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef': {}
                'k:{"name":"MYSQL_PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef': {}
                'k:{"name":"MYSQL_ROOT_PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef': {}
                'k:{"name":"MYSQL_USER"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":3306,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"mysql-data"}':
              .: {}
              'f:name': {}
              'f:persistentVolumeClaim':
                .: {}
                'f:claimName': {}
    - manager: ip-10-0-33-24
      operation: Update
      apiVersion: v1
      time: '2025-08-14T12:27:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.ovn.org/pod-networks': {}
      subresource: status
    - manager: multus-daemon
      operation: Update
      apiVersion: v1
      time: '2025-08-14T12:27:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2025-08-14T12:27:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"PodReadyToStartContainers"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:hostIPs': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.128.6.139"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: motiwolff-dev
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: mysql-65647c574b
      uid: 5f70d28c-08f6-4b0c-8b03-861f2658824d
      controller: true
      blockOwnerDeletion: true
  labels:
    deployment: mysql
    pod-template-hash: 65647c574b
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-ss6v9
  priority: -3
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-33-24.ec2.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c77,c49'
    fsGroup: 1005950000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 1000Mi
        requests:
          cpu: 10m
          memory: 64Mi
      terminationMessagePath: /dev/termination-log
      name: mysql
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1005950000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 3306
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mysql-data
          mountPath: /bitnami/mysql
        - name: kube-api-access-254jz
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'bitnami/mysql@sha256:7069480f2bd567a342ee755e9db258188114b4972b06a329b9b0d2c047659221'
  serviceAccount: default
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: pvc-skjgc
    - name: kube-api-access-254jz
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  priorityClassName: sandbox-users-pods
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: mysql
      state:
        running:
          startedAt: '2025-08-14T12:27:36Z'
      volumeMounts:
        - name: mysql-data
          mountPath: /bitnami/mysql
        - name: kube-api-access-254jz
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
          recursiveReadOnly: Disabled
      imageID: 'docker.io/bitnami/mysql@sha256:7069480f2bd567a342ee755e9db258188114b4972b06a329b9b0d2c047659221'
      image: 'docker.io/bitnami/mysql@sha256:7069480f2bd567a342ee755e9db258188114b4972b06a329b9b0d2c047659221'
      lastState: {}
      containerID: 'cri-o://1755e8e5d21f9d520e1ea52ab0bd3921b4a85ecf99540d6e79b358c0f7715708'
  qosClass: Burstable
  hostIPs:
    - ip: 10.0.33.24
  podIPs:
    - ip: 10.128.6.139
  podIP: 10.128.6.139
  hostIP: 10.0.33.24
  startTime: '2025-08-14T12:27:31Z'
  conditions:
    - type: PodReadyToStartContainers
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-08-14T12:27:37Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-08-14T12:27:31Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-08-14T12:27:37Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-08-14T12:27:37Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-08-14T12:27:31Z'
  phase: Running
